In [1]:
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import string
import nltk

df = pd.read_csv('combined_labeled_data.csv') #read csv
df

,Text,disgust,joy,anger,surprised,sad,fear,neutral
0,Come on down to Mert’s today and let us take c...,0,0,0,0,0,0,1
1,Who is Nxt ~&gt; #ChowNow lays off 20% of its ...,0,0,0,0,0,0,1
2,Chownow Layoffs\n20% Workforce\n100 Employees\...,0,0,0,0,0,0,1
3,Today’s lunch special is Smoked Pork Sausage w...,0,0,0,0,0,0,1
4,Come into Mert’s today and grab Salmon Cakes a...,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...
9277,@traik01 @WHO @cdc If only people had warmed u...,0,0,0,0,1,0,0
9278,Sorry i haven’t had any #doordash or #ubereats...,0,0,0,0,1,0,0
9279,Poor lad #UberEats https://t.co/36o565ZSc3,0,0,0,0,1,0,0
9280,One day we will all be able to bill our #UberE...,0,0,0,0,1,0,0
9281,Can someone please bless me with #DoorDash or...,0,0,0,0,1,0,0

In [2]:
def text_preprocess(s):
    '''
    lowercase, lemmatization, and removal of stop words, removal of punctuation, removal of companies
    '''
    try:
        ind = s.index('http')
        s = s[:ind]
    except:
        pass 
    
    lem=WordNetLemmatizer()
    stop_words = set(stopwords.words('english'))
    companies = set(['instacart','deliverydotcom','gopuff','grubhub','seamless','chownow','doordash','ubereats','uber eats','postmates','uber'])
    removal = stop_words.union(string.punctuation).union(companies)
    tokens = [lem.lemmatize(w.lower()) for w in nltk.word_tokenize(s) if not w.lower() in removal]
    return tokens

df['tokens'] = df.apply(lambda row: text_preprocess(row['Text']), axis=1) #apply preprocessing to create tokens
df

,Text,disgust,joy,anger,surprised,sad,fear,neutral,tokens
0,Come on down to Mert’s today and let us take c...,0,0,0,0,0,0,1,"[come, mert, ’, today, let, u, take, care, lun..."
1,Who is Nxt ~&gt; #ChowNow lays off 20% of its ...,0,0,0,0,0,0,1,"[nxt, gt, lay, 20, staff, tech, 's, latest, cu..."
2,Chownow Layoffs\n20% Workforce\n100 Employees\...,0,0,0,0,0,0,1,"[layoff, 20, workforce, 100, employee, sf, bay..."
3,Today’s lunch special is Smoked Pork Sausage w...,0,0,0,0,0,0,1,"[today, ’, lunch, special, smoked, pork, sausa..."
4,Come into Mert’s today and grab Salmon Cakes a...,0,0,0,0,0,0,1,"[come, mert, ’, today, grab, salmon, cake, two..."
...,...,...,...,...,...,...,...,...,...
9277,@traik01 @WHO @cdc If only people had warmed u...,0,0,0,0,1,0,0,"[traik01, cdc, people, warmed, u, 2, year, ago..."
9278,Sorry i haven’t had any #doordash or #ubereats...,0,0,0,0,1,0,0,"[sorry, ’, promo, code, share, lately, 😭, prom..."
9279,Poor lad #UberEats https://t.co/36o565ZSc3,0,0,0,0,1,0,0,"[poor, lad]"
9280,One day we will all be able to bill our #UberE...,0,0,0,0,1,0,0,"[one, day, able, bill, order, tmobile, bill, s..."
9281,Can someone please bless me with #DoorDash or...,0,0,0,0,1,0,0,"[someone, please, bless, dinner, 🥹]"

In [3]:
def join(li):
    return ' '.join(li)

df['Text'] = df.apply(lambda row: join(row['tokens']), axis=1) #change Text to the preprocessed version. 
df = df.loc[:,['Text','tokens','disgust', 'joy', 'anger', 'surprised', 'sad', 'fear', 'neutral']] #reorder columns
df = df[~df['Text'].isna()]
df

,Text,tokens,disgust,joy,anger,surprised,sad,fear,neutral
0,come mert ’ today let u take care lunch enjoy ...,"[come, mert, ’, today, let, u, take, care, lun...",0,0,0,0,0,0,1
1,nxt gt lay 20 staff tech 's latest cutback rb_...,"[nxt, gt, lay, 20, staff, tech, 's, latest, cu...",0,0,0,0,0,0,1
2,layoff 20 workforce 100 employee sf bay area,"[layoff, 20, workforce, 100, employee, sf, bay...",0,0,0,0,0,0,1
3,today ’ lunch special smoked pork sausage onio...,"[today, ’, lunch, special, smoked, pork, sausa...",0,0,0,0,0,0,1
4,come mert ’ today grab salmon cake two home co...,"[come, mert, ’, today, grab, salmon, cake, two...",0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
9277,traik01 cdc people warmed u 2 year ago .... sa...,"[traik01, cdc, people, warmed, u, 2, year, ago...",0,0,0,0,1,0,0
9278,sorry ’ promo code share lately 😭 promos autom...,"[sorry, ’, promo, code, share, lately, 😭, prom...",0,0,0,0,1,0,0
9279,poor lad,"[poor, lad]",0,0,0,0,1,0,0
9280,one day able bill order tmobile bill sadly tod...,"[one, day, able, bill, order, tmobile, bill, s...",0,0,0,0,1,0,0
9281,someone please bless dinner 🥹,"[someone, please, bless, dinner, 🥹]",0,0,0,0,1,0,0

In [4]:
df.to_csv('cleaned_non-vectorized_data.csv', index=False)